# Default values for PHP.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
intervalSeconds: 1
maxSurge: 25%
maxUnavailable: 25%
timeoutSeconds: 600
updatePeriodSeconds: 1
image:
  repository: docker-registry.default.svc:5000/culturagovbr/gog
  tag: 3.0.43
  pullPolicy: IfNotPresent
service:
  name: gog
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
resources:
  limits:
    cpu: '2'
