apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/culturagovbr/gog:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/culturagovbr/gog:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: gog
        chartPath: charts/gog
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/culturagovbr/gog'
          image.tag: '{{.DIGEST_HEX}}'
