apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Rolling
    rollingParams:
      intervalSeconds: {{ .Values.intervalSeconds }}
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
      timeoutSeconds: {{ .Values.timeoutSeconds }}
      updatePeriodSeconds: {{ .Values.updatePeriodSeconds }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
      annotations:
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        ports:
          - containerPort: 8080
            protocol: "TCP"
        env:
          - name: JBOSS_PASS
            value: jboss
          - name: HOSTNAMELINK
            value: 10.1.20.73
          - name: DBNAME
            value: GOG
          - name: DBUSERNAME
            value: gog
          - name: DBPASSWORD
            value: gog
          - name: DBSCHEMA
            value: ouvidoria
