apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Rolling
    rollingParams:
      intervalSeconds: {{ .Values.intervalSeconds }}
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
      timeoutSeconds: {{ .Values.timeoutSeconds }}
      updatePeriodSeconds: {{ .Values.updatePeriodSeconds }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
      annotations:
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
        ports:
          - containerPort: 8080
            protocol: "TCP"
          - containerPort: 9990
            protocol: "TCP"
        env:
          - name: JBOSS_PASS
            valueFrom:
              secretKeyRef:
                name: gog-config
                key: JBOSS_PASS
          - name: HOSTNAMELINK
            valueFrom:
              secretKeyRef:
                name: gog-config
                key: HOSTNAMELINK
          - name: DBNAME
            valueFrom:
              secretKeyRef:
                name: gog-config
                key: DBNAME
          - name: DBUSERNAME
            valueFrom:
              secretKeyRef:
                name: gog-config
                key: DBUSERNAME
          - name: DBPASSWORD
            valueFrom:
              secretKeyRef:
                name: gog-config
                key: DBPASSWORD
          - name: DBSCHEMA
            valueFrom:
              secretKeyRef:
                name: gog-config
                key: DBSCHEMA
      serviceAccountName: useroot
