apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "fullname" . }} 
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: v1
    kind: DeploymentConfig
    name: {{ template "fullname" . }} 
  targetCPUUtilizationPercentage: 70

